#!/usr/bin/env bash
# ugh
if [ $# -lt 2 ]
then
echo 'The subdomain www is a A record and points to 54.210.47.110'
echo 'The subdomain lb-01 is a A record and points to 54.210.47.110'
echo 'The subdomain web-01 is a A record and points to 34.198.248.145'
echo 'The subdomain web-02 is a A record and points to 54.89.38.100'
else
echo 'The subdomain www is a A record and points to 54.210.47.110'
fi
