#!/usr/bin/env bash
# set up nginx

# install nginx
sudo apt-get update
sudo apt-get -y install nginx

# make html directory
sudo mkdir -p /var/www/html/
echo "Holberton School" | sudo tee -a /var/www/html/index.html

# start nginx
sudo service nginx start