#!/usr/bin/env bash
# set up redirect

# update
sudo apt-get -y update
sudo apt-get -y install nginx

sudo ufw allow "Nginx HTTP"
cd /etc/nginx/sites-available/ || exit
sudo sed -i "s!server_name _;!server_name _;\n\tlocation /redirect_me \{\n\t\treturn 301 https://www.youtube.com/watch?v=ic_iClOg34A;\n\t}!" default
sudo service nginx restart