#!/usr/bin/env bash
# set up headers

sudo apt-get -y update
sudo apt-get -y install nginx

sudo sed -i "30i	add_header X-Served-By $HOSTNAME;" /etc/nginx/sites-enabled/default
sudo service nginx reload
