#!/usr/bin/env bash
# set up load balancer

sudo apt-get update
sudo apt-get install -y haproxy

echo '
frontend owo
	bind *:80
	mode http
	default_backend uwu
backend uwu
	balance roundrobin
	option forwardfor
		server 821-web-01 35.231.144.105
		server 821-web-02 34.74.125.205
' | sudo tee -a /etc/haproxy/haproxy.cfg

sudo service haproxy restart
