#!/usr/bin/env bash
# never gonna give you up XD

echo $$ | sudo tee /var/run/holbertonscript.pid > /dev/null
trap "echo 'y U no love me?!'" SIGINT
trap "echo 'I hate the kill command' ; rm /var/run/holbertonscript.pid ; exit" SIGTERM
trap "rm /var/run/holbertonscript.pid ; exit" SIGQUIT
while true ; do
	 echo "To infinity and beyond"
done
