#!/usr/bin/env bash
# fix nginx
sudo pkill apache2
sudo pkill nginx
sudo chown nginx:nginx /etc/nginx/nginx.conf
sudo chmod u+r /etc/nginx/nginx.conf
sudo sed -i "s/80 /8080 /" /etc/nginx/sites-enabled/default
sudo -u nginx service nginx start
