#!/usr/bin/env bash
# fix nginx
sudo pkill nginx
sudo chown nginx /etc/nginx/nginx.conf
sudo chmod u+r /etc/nginx/nginx.conf
sudo sed -i 's/80/8080/' /etc/nginx/sites-enabled/default
sudo -u nginx service nginx start
